### ISSUE TITLE
Går ej att lämna, ifall man skriver 3 för att acceptera hamnar man i spelet igen

### ISSUE THREAD

**Issue by Papput** [MrGumba/pytonTe19#3]
https://github.com/MrGumba/pytonTe19/blob/042dee74f2d67f766435ed9315967bba04e50963/MineSweeper.py#L26

![image](https://user-images.githubusercontent.com/15913948/115908585-a6fcb500-a46a-11eb-9c2a-76aeda38a364.png)

**Comment by Papput** [comment]
Funkar dock att byta svårighets grad eftar man lämnat, så är något med att acceptera att man vill avsluta som är på tok

![image](https://user-images.githubusercontent.com/15913948/115908840-f80ca900-a46a-11eb-8156-d7c01cc29229.png)

**Comment by MrGumba** [comment]
fixade detta problem genom att ändra return till exit()
